from . import vessel_cargo_type
from . import vessel_charter_terms
from . import vessel_laytime_interruption_type
from . import res_partner
from . import vessel_charter_contract
from . import vessel_voyage_estimate
from . import vessel_sof_line
from . import vessel_laytime_calculation
from . import vessel_offhire_event
from . import vessel_hire_statement_line
from . import account_move
from . import res_company
from . import fleet_vehicle
